/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WhyBuildThisImport } from './routes/why-build-this'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const WhyBuildThisRoute = WhyBuildThisImport.update({
  path: '/why-build-this',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/why-build-this': {
      id: '/why-build-this'
      path: '/why-build-this'
      fullPath: '/why-build-this'
      preLoaderRoute: typeof WhyBuildThisImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  WhyBuildThisRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/why-build-this"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/why-build-this": {
      "filePath": "why-build-this.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
